### ISSUE TITLE
http://rst.ninjs.org/ is out of date

### ISSUE THREAD

**Issue by jessamynsmith** [anru/rsted#33]
A number of RST markup directives are not recognized on the website http://rst.ninjs.org/ although they work fine on a local installation with the latest versions of all dependencies. Any chance you'll update the site?

Great project, by the way, I have found it super useful for getting my README files in shape for PyPI.

**Comment by anru** [comment]
Oh, sure. I'm updating packages right now

**Comment by anru** [comment]
Updated.
